parameters:
  agentPool: ''
  env: ''
  armServiceConnectionName: ''
  failoverDeployment: false
  outputsFileName: ''
  runTerraformApply: false
  refreshTFState: false


##
# Deploy Infrastructure
##
jobs:
- job: DeployInfrastructureJob
  pool: ${{ parameters.agentPool }}
  timeoutInMinutes: 0 # Max timeout
  steps:
  ###
  # Validation phase
  ###

  # Checkout repo
  - checkout: self
    displayName: 'Checkout Repo'
  
  - script: |
      export PATH="$PATH:/home/AzDevOps/.local/bin/"
      python3 -m pytest $(Build.SourcesDirectory)/pipelines/scripts/test_script.py
    displayName: 'test script'
