name: Break Terraform State Lease

# a basic pipeline to break the state lease if present
parameters:
- name: env
  default: 'build'
  values:
  - 'build'
  - 'dev'
  - 'test'
  - 'prod'

# no automatic runs
pr: none
trigger: none

stages:
  - stage: run
    jobs:
      - deployment: BreakLease
        displayName: Break tf lease
        pool: 'pins-agent-pool-odw-${{ parameters.env }}-uks'
        environment: ${{ parameters.env }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: "Break lease on terraform state"
                  name: BreakLease
                  inputs:
                    azureSubscription: "Azure Devops Pipelines - ODW ${{ upper(parameters.env) }} - Infrastructure"
                    scriptType: "pscore"
                    scriptLocation: "inlineScript"
                    inlineScript: "az storage blob lease break --container-name 'terraformstate-odw' --blob-name '${{ parameters.env }}.tfstate' --account-name 'pinsstsharedtfstateuks' --subscription 'edb1ff78-90da-4901-a497-7e79f966f8e2' --auth-mode login"